packages:
  - api

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - cpu-features
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - ssh2
